import type { PublicSnapshot } from "@/types/content";

const now = "2026-09-04T15:00:00.000Z";

export const demoSnapshot: PublicSnapshot = {
  source: "demo",
  artists: [
    {
      id: "demo-artist-andrea",
      slug: "andrea-perfil-conceptual",
      name: "Andrea — perfil conceptual",
      stage_name: null,
      excerpt: "Ficha demostrativa de una artista aérea. La información real queda pendiente de aprobación.",
      bio: "Este perfil sirve para validar la experiencia editorial. Andrea aparece únicamente como caso conceptual de una artista aérea que trabaja tela, lira y trapecio.",
      disciplines: ["Tela", "Lira", "Trapecio"],
      experience: ["Experiencia a completar con información autorizada"],
      training: ["Formación a completar con información autorizada"],
      social_links: {},
      cv_url: null,
      seo_title: "Andrea — perfil conceptual",
      seo_description: "Perfil de demostración para la experiencia de artistas de Compañía Turnoc.",
      updated_at: now,
    },
  ],
  projects: [
    {
      id: "demo-project-air",
      slug: "cartografia-del-aire-demo",
      title: "Cartografía del aire — demo",
      excerpt: "Una pieza provisional para probar la relación entre obra, elenco, archivo y agenda.",
      synopsis: "Una silueta se eleva, otra sostiene el tiempo. Este texto es completamente demostrativo: será reemplazado por la voz y los materiales reales de Compañía Turnoc.",
      state: "current",
      year_start: 2026,
      year_end: null,
      booking_enabled: true,
      artistic_sheet: { Dirección: "A confirmar", Duración: "A confirmar" },
      technical_sheet: { Espacio: "Adaptable — dato demo", Público: "A confirmar" },
      press_mentions: [],
      awards: [],
      seo_title: "Cartografía del aire — proyecto demo",
      seo_description: "Proyecto de demostración para validar la arquitectura pública de Compañía Turnoc.",
      updated_at: now,
    },
  ],
  events: [
    {
      id: "demo-event-lab",
      slug: "laboratorio-abierto-demo",
      title: "Laboratorio abierto — fecha demo",
      kind: "workshop",
      excerpt: "Fecha provisional para validar la agenda. No constituye una actividad real.",
      description: "Una instancia ficticia de intercambio y exploración escénica.",
      venue: "Espacio a confirmar",
      city: "Ciudad a confirmar",
      starts_at: "2026-11-14T21:00:00.000Z",
      ends_at: null,
      external_url: null,
      project_id: "demo-project-air",
      artist_id: null,
      updated_at: now,
    },
  ],
  posts: [
    {
      id: "demo-post-notebook",
      slug: "cuaderno-de-altura-demo",
      title: "Cuaderno de altura — demo",
      kind: "backstage",
      excerpt: "Una entrada editorial ficticia para probar el archivo vivo del sitio.",
      body: "Acá podrá convivir la investigación, el proceso creativo y la memoria de cada obra. Este contenido es demostrativo y no atribuye declaraciones a personas reales.",
      tags: ["proceso", "archivo"],
      cta_label: null,
      cta_url: null,
      closes_at: null,
      project_id: "demo-project-air",
      artist_id: null,
      seo_title: "Cuaderno de altura — contenido demo",
      seo_description: "Entrada de demostración del archivo editorial de Compañía Turnoc.",
      publish_at: now,
      updated_at: now,
    },
    {
      id: "demo-post-call",
      slug: "convocatoria-laboratorio-demo",
      title: "Convocatoria a laboratorio — demo",
      kind: "call",
      excerpt: "Convocatoria ficticia destinada a comprobar el circuito de lectura y moderación.",
      body: "Este contenido no representa una convocatoria vigente. La versión final incluirá bases, plazos y contacto aprobados.",
      tags: ["convocatoria", "comunidad"],
      cta_label: "Enviar una propuesta",
      cta_url: "/comunidad#proponer",
      closes_at: null,
      project_id: null,
      artist_id: null,
      seo_title: "Convocatoria — contenido demo",
      seo_description: "Convocatoria de demostración para la comunidad de lectura de Turnoc.",
      publish_at: now,
      updated_at: now,
    },
  ],
  features: [
    {
      id: "demo-feature-hero",
      slot: "hero",
      eyebrow: "Circo contemporáneo · contenido demo",
      title: "El riesgo también puede ser una forma de memoria.",
      summary: "Una portada provisional para probar ritmo, contraste y movimiento antes de incorporar la identidad real.",
      entity_type: "project",
      entity_id: "demo-project-air",
      href: "/proyectos/cartografia-del-aire-demo",
      sort_order: 0,
    },
  ],
  credits: [
    {
      project_id: "demo-project-air",
      artist_id: "demo-artist-andrea",
      role_name: "Artista aérea — crédito demo",
      sort_order: 0,
    },
  ],
};
