import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ContentCard } from "@/components/content-card";
import { SourceBanner } from "@/components/source-banner";
import { projectStateLabels } from "@/lib/format";
import { getProjectBySlug, getPublicSnapshot } from "@/lib/supabase/data";
import { absoluteUrl, jsonLd } from "@/lib/seo";

type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const project = await getProjectBySlug(slug); if (!project) return { title: "Proyecto no encontrado" }; return { title: project.seo_title ?? project.title, description: project.seo_description ?? project.excerpt, alternates: { canonical: `/proyectos/${project.slug}` }, openGraph: { title: project.seo_title ?? project.title, description: project.seo_description ?? project.excerpt, url: `/proyectos/${project.slug}`, type: "website" } }; }

function jsonFacts(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return []; return Object.entries(value as Record<string, unknown>).map(([label, content]) => [label, String(content)] as const); }

export default async function ProjectDetailPage({ params }: Props) {
  const { slug } = await params; const [project, snapshot] = await Promise.all([getProjectBySlug(slug), getPublicSnapshot()]); if (!project) notFound();
  const artistIds = new Set(snapshot.credits.filter((credit) => credit.project_id === project.id).map((credit) => credit.artist_id));
  const artists = snapshot.artists.filter((artist) => artistIds.has(artist.id)); const events = snapshot.events.filter((event) => event.project_id === project.id); const posts = snapshot.posts.filter((post) => post.project_id === project.id);
  const schema = { "@context": "https://schema.org", "@type": "TheaterEvent", name: project.title, description: project.excerpt, url: absoluteUrl(`/proyectos/${project.slug}`), organizer: { "@type": "PerformingGroup", name: "Compañía Turnoc" } };
  return <main id="contenido"><SourceBanner source={snapshot.source} /><article><header className="detail-hero"><div className="site-shell"><span className="eyebrow">{projectStateLabels[project.state]}</span><h1 className="display page-title">{project.title}</h1><div className="detail-kicker">{project.year_start ? <span className="pill">Desde {project.year_start}</span> : null}{project.booking_enabled ? <span className="pill">Disponible para contratación</span> : null}</div><p className="lede">{project.excerpt}</p><div className="button-row">{project.booking_enabled ? <Link className="button button-primary" href={`/contacto?proyecto=${project.slug}`}>Consultar contratación</Link> : null}</div></div></header><div className="site-shell detail-body split"><div><span className="eyebrow">Sinopsis</span><h2 className="display section-title">La obra.</h2></div><div className="prose"><p>{project.synopsis || "La sinopsis aprobada todavía no fue cargada."}</p><dl className="fact-list">{jsonFacts(project.artistic_sheet).map(([label, value]) => <div className="fact-row" key={label}><dt>{label}</dt><dd>{value}</dd></div>)}{jsonFacts(project.technical_sheet).map(([label, value]) => <div className="fact-row" key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></div></article><section className="section section-paper"><div className="site-shell"><div className="section-heading"><h2 className="display section-title">Elenco y equipo.</h2></div><div className="card-grid">{artists.length ? artists.map((artist, index) => <ContentCard index={index} eyebrow="Artista" title={artist.stage_name ?? artist.name} copy={artist.excerpt} href={`/artistas/${artist.slug}`} tags={artist.disciplines} key={artist.id} />) : <div className="empty-state">El elenco publicado aparecerá acá.</div>}</div></div></section><section className="section section-dark"><div className="site-shell split"><div><span className="eyebrow">Agenda y archivo</span><h2 className="display section-title">Lo que rodea a la obra.</h2></div><div className="prose"><p>{events.length} fecha(s) publicada(s) · {posts.length} pieza(s) editorial(es).</p><div className="button-row"><Link className="button button-quiet" href="/agenda">Ver agenda</Link><Link className="button button-quiet" href="/actualidad">Leer actualidad</Link></div></div></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(schema) }} /></main>;
}
