import Link from "next/link";
import { ContentCard } from "@/components/content-card";
import { SourceBanner } from "@/components/source-banner";
import { formatDateTime, postKindLabels, projectStateLabels } from "@/lib/format";
import { getPublicSnapshot } from "@/lib/supabase/data";

export default async function HomePage() {
  const snapshot = await getPublicSnapshot();
  const feature = snapshot.features.find((item) => item.slot === "hero") ?? snapshot.features[0];
  const hero = feature ?? { eyebrow: "Compañía Turnoc", title: "Cuerpos en riesgo. Historias en movimiento.", summary: "Archivo, escena y comunidad en un mismo espacio.", href: "/proyectos" };
  return <main id="contenido" className="site-main"><SourceBanner source={snapshot.source} /><section className="hero"><div className="hero-orbit" aria-hidden="true" /><div className="site-shell hero-grid"><div className="hero-copy" data-reveal><span className="eyebrow">{hero.eyebrow}</span><h1 className="display hero-title">{hero.title}</h1></div><div className="hero-aside" data-reveal><div className="hero-index" aria-hidden="true">01</div><p className="lede">{hero.summary}</p><div className="button-row"><Link className="button button-primary" href={hero.href}>Entrar en escena</Link><Link className="button button-quiet" href="/contacto">Contratar</Link></div></div></div></section><div className="ticker" aria-hidden="true"><div className="ticker-track"><span>Obras · Artistas · Archivo · Comunidad · Agenda ·</span><span>Obras · Artistas · Archivo · Comunidad · Agenda ·</span></div></div>
    <section className="section section-dark"><div className="site-shell"><div className="section-heading" data-reveal><div><span className="eyebrow">Obras</span><h2 className="display section-title">Ahora y siempre.</h2></div><p className="lede">Los proyectos viven en presente, futuro y archivo; cada ficha reúne escena, equipo, memoria y contratación.</p></div><div className="card-grid">{snapshot.projects.length ? snapshot.projects.slice(0, 3).map((project, index) => <ContentCard key={project.id} index={index} eyebrow={projectStateLabels[project.state]} title={project.title} copy={project.excerpt} href={`/proyectos/${project.slug}`} />) : <div className="empty-state">La programación publicada aparecerá acá.</div>}</div></div></section>
    <section className="section section-paper"><div className="site-shell split"><div data-reveal><span className="eyebrow" style={{ color: "var(--coral)" }}>Próximamente</span><h2 className="display section-title">Encontrarnos en tiempo real.</h2><p className="lede">Funciones, talleres, festivales y conversaciones, sin obligar a nadie a crear una cuenta.</p><Link className="button button-coral" href="/agenda">Ver agenda completa</Link></div><div className="timeline">{snapshot.events.length ? snapshot.events.slice(0, 4).map((event) => <Link className="timeline-item" href="/agenda" key={event.id}><span className="timeline-year">{formatDateTime(event.starts_at)}</span><span><strong>{event.title}</strong><br />{event.venue} · {event.city}</span></Link>) : <div className="empty-state">No hay fechas publicadas todavía.</div>}</div></div></section>
    <section className="section section-dark"><div className="site-shell"><div className="section-heading" data-reveal><div><span className="eyebrow">Actualidad</span><h2 className="display section-title">Lo que pasa detrás.</h2></div><Link className="button button-quiet" href="/actualidad">Abrir el archivo</Link></div><div className="card-grid">{snapshot.posts.length ? snapshot.posts.slice(0, 3).map((post, index) => <ContentCard key={post.id} index={index} eyebrow={postKindLabels[post.kind]} title={post.title} copy={post.excerpt} href={`/actualidad/${post.slug}`} tags={post.tags} />) : <div className="empty-state">Las publicaciones editadas aparecerán acá.</div>}</div></div></section>
    <section className="section section-paper"><div className="site-shell split"><div><span className="eyebrow" style={{ color: "var(--coral)" }}>Comunidad de lectura</span><h2 className="display section-title">Curar también es hacer cultura.</h2></div><div className="prose"><p>Agenda seleccionada, convocatorias y recursos para leer el circo más allá de una función.</p><p>Las propuestas ingresan a una bandeja moderada. Nada se publica automáticamente.</p><Link className="button button-coral" href="/comunidad">Sumar una propuesta</Link></div></div></section></main>;
}
